### ISSUE TITLE
hash_sha256 getting different result from other library. 

### ISSUE THREAD

**Issue by glennpierce** [monolifed/pbkdf2-hmac-sha256#2]
Hi I am trying to get the same result for a hmax_sha256 sign from a couple of other libraries.

for example in rust I have something like

let key: ring::hmac::Key = ring::hmac::Key::new(ring::hmac::HMAC_SHA256, &salted_passwd);
let signed_client_key = ring::hmac::sign(&key, "Client Key".as_bytes());
println!("signed_client_key: {:X?}", signed_client_key);

the salted password is 524c82435601f99701939a2ed2e1876ddf6875696e29cfc4208f23a0d521a0a7
and the result I get is
11b407ef4f01534a138a8599545dc3c943535dac95477d7f1334fec85408197c

I also have a js lib that produces the same result.

How can I sign something with 
pbkdf2-hmac-sha256

I have done something like 

```
void hash_sha256(HMAC_SHA256_CTX *hmac,
    const uint8_t *key, const uint8_t *data, uint8_t *dk)
{
	uint32_t key_len = strlen((const char*)key);
	hmac_sha256_init(hmac, key, key_len);
	hmac_sha256_update(hmac, data, strlen((const char*)data));
	hmac_sha256_final(hmac, dk);
}

const uint8_t *salted_passwd = (const uint8_t*) "524c82435601f99701939a2ed2e1876ddf6875696e29cfc4208f23a0d521a0a7";
hash_sha256(&hmac2, salted_passwd, (const uint8_t*) "Client Key", dk2,);

Any idea why I get a different result ?
ie
CE B9 16 D4 DB 29 95 94 C9 58 FF 77 64 93 E2 97 60 FC 3B DA F5 A5 C5 56 CE BB 7B FE D 60 41 8A


Note I have got pbkdf2_sha256 agreeing so I think I misunderstand something with respect to "sign" of the other libraries.

Thanks


```

**Comment by monolifed** [comment]
I believe it is because you are passing a hex (encoded) string. It can be:  
`const uint8_t *salted_passwd = (const uint8_t*) "\x52\x4c\x82..."; `
or  
`const uint8_t salted_passwd[] = {0x52, 0x4c, 0x82, ...}; `

**Comment by glennpierce** [comment]
Yes that was it . Thanks
